#!/usr/bin/with-contenv sh

if [ "$HOMEBRIDGE_CONFIG_UI" = "1" ]; then
  echo "Enabling homebridge-config-ui-x-hoobs..."
  # enable homebridge-config-ui-x-hoobs service
  [ -e /etc/services.d/homebridge-config-ui-x-hoobs ] || mv /etc/services.d/.homebridge-config-ui-x-hoobs /etc/services.d/homebridge-config-ui-x-hoobs
else
  # disable homebridge-config-ui-x-hoobs service
  [ -e /etc/services.d/homebridge-config-ui-x-hoobs ] && mv /etc/services.d/homebridge-config-ui-x-hoobs /etc/services.d/.homebridge-config-ui-x-hoobs

  # Remove pre-installed homebridge-config-ui-x-hoobs plugin
  [ -e /usr/local/lib/node_modules/homebridge-config-ui-x-hoobs ] && npm uninstall -g homebridge-config-ui-x-hoobs
fi

# check homebridge-config-ui-x-hoobs is not installed in /homebridge/node_modules when enabled with the HOMEBRIDGE_CONFIG_UI flag
if [ "$HOMEBRIDGE_CONFIG_UI" = "1" ]; then
  [ -e /homebridge/node_modules/homebridge-config-ui-x-hoobs ] && npm uninstall --save homebridge-config-ui-x-hoobs
fi
